### ISSUE TITLE
Ability to group multi-disc releases in a single folder

### ISSUE THREAD

**Issue by the-confessor** [whipper-team/whipper#448] opened 2020-01-11 19:59 UTC
When I rip a multi-disc release I would like the content to all end up in a single folder. 

It might be as simple as providing a couple more template options - the disc number, and the release title (i.e. the title of the release, not a title for the individual disc within the release).

e.g. let's us an example - [Det bästa med Monica Zetterlund](https://musicbrainz.org/release/56cbfbe6-e6c2-4074-9fab-9f497a2379b2/discids)

Currently when I rip this with whipper I end up with two separate folders. (Limiting the examples to 1 file per folder)

```
Monica Zetterlund - Det bästa med Monica Zetterlund (Disc 1 of 2)/01 - Att angöra en brygga.flac
Monica Zetterlund - Det bästa med Monica Zetterlund (Disc 2 of 2)/01 - Bedårande sommarvals.flac
```

But I would rather see the discs contained in subfolders under one parent:

```
Monica Zetterlund - Det bästa med Monica Zetterlund/Disc 1/01 - Att angöra en brygga.flac
Monica Zetterlund - Det bästa med Monica Zetterlund/Disc 2/01 - Bedårande sommarvals.flac
```

Or potentially even all in one folder, using the file name to identify the disc:

```
Monica Zetterlund - Det bästa med Monica Zetterlund/D1 - 01 - Att angöra en brygga.flac
Monica Zetterlund - Det bästa med Monica Zetterlund/D2 - 01 - Bedårande sommarvals.flac
```

I think the additional template options would help me achieve this.

**Comment by JoeLametta** [comment] 2020-01-14 18:27
I like this idea but keep in mind this is a low priority issue.

> the release title (i.e. the title of the release, not a title for the individual disc within the release)

This specific request seems to be a duplicate of #440.

**Comment by the-confessor** [comment] 2020-01-15 16:46
After digging into the code a bit I noticed that whipper has a hard hard coding behavior of appending the disc number to the release title for multi-disc releases. 

from mbngs.py:

```python
                count = len(release['medium-list'])
                if count > 1:
                    title += ' (Disc %d of %d)' % (
                        int(medium['position']), count)
```

All I would need to achieve what I want is to have the disc number as a separate template and not automatically appended, so I can choose where it goes.

However realizing that some people may depend on the current behavior would make this an interesting change to roll out. The choice to not append the disc number to the release title would have to be controlled via some kind of flag, enabled by default.

I think it's very similar in nature to the hard coded usage of disambiguation title, but not identical.

**Comment by JoeLametta** [comment] 2020-01-16 09:17
> I think it's very similar in nature to the hard coded usage of disambiguation title, but not identical.

You're right. This issue is currently scheduled for milestone 2.0 but if I have enough time I'll try to complete it for milestone 1.0 :wink

**Closed** 2021-05-16 10:48 UTC
Labels: Accepted, Feature, Priority: low, Sprintable
