### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by shibumi** [whipper-team/whipper#202] opened 2017-10-22 01:04 UTC
Hello while ripping I got this error:
```
Ripping track 13 of 15: 13. ギルガメッシュ - smash!!.flac
WARNING:morituri.program.cdparanoia:file size 0 did not match expected size 31695596
WARNING:morituri.program.cdparanoia:non-integral amount of frames difference
Traceback (most recent call last):         
  File "/usr/lib/python2.7/site-packages/morituri/extern/task/task.py", line 511, in c
    callable(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/morituri/program/cdparanoia.py", line 316, in _read
    self._done()
  File "/usr/lib/python2.7/site-packages/morituri/program/cdparanoia.py", line 390, in _done
    self.quality = self._parser.getTrackQuality()
  File "/usr/lib/python2.7/site-packages/morituri/program/cdparanoia.py", line 201, in getTrackQuality
    return min(frames * 2.0 / reads, 1.0)
ZeroDivisionError: float division by zero
```

I ripped the following CD: https://musicbrainz.org/cdtoc/attach?toc=1+15+207849+150+5169+20758+33837+47664+61612+79296+85118+97961+111683+127452+143271+158135+171611+189951&tracks=15&id=q6de1TGfhajKLUYfGFUtRxYn9VI-

**Comment by nicksinger** [comment] 2017-11-17 10:00
Are you sure you're on the most recent version of whipper? https://github.com/JoeLametta/whipper/pull/159 fixed at least the hard crash here.
However I'd be interesting to know if your drive works properly because this happens if nothing could be read off the CD (reads == 0, therefore a division by zero). I encountered this error with a faulty CD drive.

Could you try the plain old cdparanoia to rip the same disk with the same drive again? Because if this works, the problem is maybe more deeply hidden in whipper.

**Comment by shibumi** [comment] 2017-11-18 15:40
Yep I am on version 0.5.1 (your last official release). The funny part is that I can still rip the CD without any broken song. whipper will just rip the song again and then it suddenly works. The accuraterip database entry looks also good for that CD.

I don't think the CD drive is broken. It's new and just a couple of days old. I ordered it explicitly for the use with whipper.

Where can I find the plain old cdparanoia?

**Comment by JoeLametta** [comment] 2018-04-06 15:08
@shibumi Whipper `v0.6.0` has the commit linked in #159: that exception shouldn't raise anymore.

I'm keeping this issue open because, before closing it, I'd like to be sure we're not ignoring a deeper problem in whipper.

**Comment by JoeLametta** [comment] 2018-11-03 15:18
Old discussion is available in https://github.com/thomasvs/morituri/issues/46.
I think I'm going to revert this change because it doesn't seem related to hardware issues and may mask other existing problems too.

**Comment by shibumi** [comment] 2018-11-04 16:35
@JoeLametta shall I rip the CD and check if the error still exist?

**Closed** 2018-11-09 20:52 UTC
Labels: bug, completed
