### ISSUE TITLE
whipper image verify says it's not accurate even though...

### ISSUE THREAD

**Issue by wooptoo** [whipper-team/whipper#339] opened 2018-11-25 23:52 UTC
Hi

I'm running into an issue where I'm ripping a CD with the results initially reported as accurate for all tracks, but the subsequent `whipper image verify *.cue` check fails for all. 
After re-ripping the same CD with EAC on windows the CRC and the AR2 checksums seem to be the same for each track.
Here is a diff between EAC logs and whipper with the eac log plugin:

https://www.diffchecker.com/MVlqmjTi

So i believe my whipper rip is actually good, just the verification somehow failing?
This is whipper 0.7.2 on kernel 4.19.2-arch1-1-ARCH
What I've noticed during the rip is that the hidden track 0 is detected (and ignored?) by whipper.

**Comment by jtl999** [comment] 2018-11-26 22:34
Hmm (using a build from recent git commits)

```
root@cdripper:/rips/Red Hot Chili Peppers/Blood Sugar Sex Magik# whipper image verify Blood\ Sugar\ Sex\ Magik.cue 
track  1: rip accurate     (confidence  19 of  23) v1 [cd2e3b53], v2 [3d05abcf], DB [cd2e3b53, 3d05abcf]
track  2: rip accurate     (confidence  18 of  23) v1 [6b6606e6], v2 [1141cfa4], DB [6b6606e6, 1141cfa4]
track  3: rip accurate     (confidence  19 of  23) v1 [92f7c16d], v2 [12635e47], DB [92f7c16d, 12635e47]
track  4: rip accurate     (confidence  19 of  22) v1 [d3f99647], v2 [f1af0b5c], DB [d3f99647, f1af0b5c]
track  5: rip accurate     (confidence  19 of  23) v1 [e2f961fe], v2 [7402b60b], DB [e2f961fe, 7402b60b]
track  6: rip accurate     (confidence  18 of  23) v1 [69375aca], v2 [6b288e13], DB [69375aca, 6b288e13]
track  7: rip accurate     (confidence  18 of  22) v1 [c49daa2f], v2 [1e336d9b], DB [c49daa2f, 1e336d9b]
track  8: rip accurate     (confidence  19 of  23) v1 [36ae6418], v2 [9a846af2], DB [36ae6418, 9a846af2]
track  9: rip accurate     (confidence  19 of  22) v1 [5d3c9b0a], v2 [6c4a4faf], DB [5d3c9b0a, 6c4a4faf]
track 10: rip accurate     (confidence  19 of  23) v1 [eb2c0a24], v2 [8aaab586], DB [eb2c0a24, 8aaab586]
track 11: rip accurate     (confidence  20 of  23) v1 [51ee77ea], v2 [ca26978f], DB [51ee77ea, ca26978f]
track 12: rip accurate     (confidence  20 of  23) v1 [0c0ed914], v2 [663d53b1], DB [0c0ed914, 663d53b1]
track 13: rip accurate     (confidence  18 of  23) v1 [699e041c], v2 [33240847], DB [699e041c, 33240847]
track 14: rip accurate     (confidence  17 of  23) v1 [b2c525cf], v2 [86fd190e], DB [b2c525cf, 86fd190e]
track 15: rip accurate     (confidence  16 of  22) v1 [7fc35258], v2 [93d2f5e1], DB [7fc35258, 93d2f5e1]
track 16: rip accurate     (confidence  16 of  20) v1 [ed1b426c], v2 [5436c775], DB [ed1b426c, 5436c775]
track 17: rip accurate     (confidence  18 of  23) v1 [dd24d799], v2 [a97e21f4], DB [dd24d799, a97e21f4]
```

**Comment by jtl999** [comment] 2018-11-28 22:57
Trying a rip with just above silent HTOA audio

```
root@cdripper:/rips/The Marshall Tucker Band/Together Forever# whipper image verify Together\ Forever.cue 
track  1: rip accurate     (max confidence      5) v1 [19d9299c], v2 [e3f13cc7], DB [19d9299c, e3f13cc7]
track  2: rip accurate     (max confidence      5) v1 [751edb26], v2 [87b3742a], DB [751edb26, 87b3742a]
track  3: rip accurate     (max confidence      5) v1 [b0fd8765], v2 [46b01f05], DB [b0fd8765, 46b01f05]
track  4: rip accurate     (max confidence      5) v1 [e5aec748], v2 [75ee5311], DB [e5aec748, 75ee5311]
track  5: rip accurate     (max confidence      5) v1 [1ddbbed1], v2 [58cb5be5], DB [1ddbbed1, 58cb5be5]
track  6: rip accurate     (max confidence      5) v1 [fc0c8b2f], v2 [332c0234], DB [fc0c8b2f, 332c0234]
track  7: rip accurate     (max confidence      5) v1 [74047a46], v2 [3e7ee401], DB [74047a46, 3e7ee401]
```

**Comment by JoeLametta** [comment] 2018-11-29 11:54
Thanks @wooptoo for reporting this issue and @jtl999 for the tests.
This report seems to be a duplicate of #239, let's keep discussing it there.

**Closed by JoeLametta** 2018-11-29 11:54 UTC
Labels: Bug, Duplicate
