### ISSUE TITLE
Add option to limit drive speed

### ISSUE THREAD

**Issue by unkissedfrog** [whipper-team/whipper#473] opened 2020-03-07 17:30 UTC
Dear all, 

I love to reduce the drive speed for ripping audio CDs e.g. with `hdparm -E`. I noticed whipper to ignore this setting. The `reading TOC ` process works fine with the reduced speed but when it comes to read/compare the tracks, my drive spins up again and gets noisy. 
I verified this with all my drives. 

Can you help please? Or can you add an option to set the drive speed with whipper? 

Thanks for help

**Comment by JoeLametta** [comment] 2020-03-07 17:49
Hi, whipper currently relies on two programs in order to rip CDs:
1. cdrdao (toc extraction)
2. cd-paranoia (audio ripping)

It seems you're saying that cdrdao does respec the drive speed set through hdparm while cd-paranoia doesn't. If that's correct you could try asking @rocky if there's a way to let cd-paranoia automatically detect and obey to that limit.
Another solution would be adding an option to whipper to limit the maximum drive speed. The user provided value would then be propagated both to cdrdao and cd-paranoia.

cdrdao setting:
```
--rspeed <read-speed>   - selects reading speed
```

cd-paranoia setting:
```
-S --force-read-speed number
        Use this option explicitly to set the read rate of the CD drive
        (where supported).  This can reduce underruns on machines with
        slow disks, or which are low on memory.
```

**Comment by rocky** [comment] 2020-03-07 21:37
Some information on libcdio-paranoia...

In contrast to [cdparanoia](https://www.xiph.org/paranoia), cd-paranoia relies on [GNU libcdio](https://www.gnu.org/software/libcdio/) for anything hardware related; cd-paranoia just has the more algorithmically-oriented and hardware independent parts where it looks for jitter by analyzing sound data that comes back, looking for silence or blank gaps in that. 

I just looked at the libcdio API and there is nothing in there for _detecting_ speed across the OS's that are supported, only _setting_ the speed. If the CD-ROM drive supports the MMC-command set (which is supposed to be a "standard") then it _might_ come back and tell you what the manufacter has decided the speed is, _if_ the manufacture has added a "profile" for that feature. The profile information is optional. And even here, as it says in the [cdparanoia FAQ](https://www.xiph.org/paranoia/faq.html#play):
> _Note that CD 'playback speed' is an excellent example of advertisers making numbers lie for them._

Given this, although this may sound self serving, the best thing to do would be for the speed to be passed along to cd-paranoia.

**Comment by unkissedfrog** [comment] 2020-03-08 11:06
I think adding an "force drive speed" option to whipper would be great and very welcome!

I just played around with the cdparanoia -S setting and my drive does not spin up so it seems to respect this flag.

**Comment by JoeLametta** [comment] 2020-03-22 15:40
@rocky Thanks for the reply!

> I think adding an "force drive speed" option to whipper would be great and very welcome!

I agree and I'm going to change the title of this issue to reflect this.

**Comment by JoeLametta** [comment] 2021-05-16 09:05
Duplicate of #204: I'm closing this one. Let's continue the discussion in the other issue.

**Closed by JoeLametta** 2021-05-16 09:05 UTC
Labels: Accepted, Duplicate, Feature, Priority: medium
