### ISSUE TITLE
Whipper fails with AttributeError: 'NoneType' object has no attribute 'path'

### ISSUE THREAD

**Issue by janifr** [whipper-team/whipper#350] opened 2018-12-25 19:57 UTC
Hi,
I just installed debian testing and whipper 0.7.3 from deb-multimedia. I'm getting the following error:

jani@ripperi:~$ whipper cd rip
INFO:whipper.command.cd:using configured read offset 6
INFO:whipper.command.cd:checking device /dev/sr0
INFO:whipper.command.cd:reading TOC...
CDDB disc id: e0100f0f
MusicBrainz disc id 1sOmm3YBExqtJigMpphyt1v.Xj0-
MusicBrainz lookup URL https://musicbrainz.org/cdtoc/attach?toc=1+15+308490+183+19160+34320+51448+69190+90953+110213+139555+168450+186075+203230+219173+235405+252570+277288&tracks=15&id=1sOmm3YBExqtJigMpphyt1v.Xj0-
Disc duration: 01:08:30.760, 15 audio tracks
INFO:musicbrainzngs:in <ws2:release-group>, uncaught attribute type-id
INFO:musicbrainzngs:in <ws2:release-group>, uncaught attribute type-id

Matching releases:

Artist  : Scorpions
Title   : Best of Rockers ’n’ Ballads
Duration: 01:08:58.291
URL     : https://musicbrainz.org/release/235241ed-f7dc-47a4-b2c6-02ef57c2d587
Release : 235241ed-f7dc-47a4-b2c6-02ef57c2d587
Type    : Compilation
Barcode : 724353469320
Cat no  : 7243 5 34693 2 0

Artist  : Scorpions
Title   : Best of Rockers ’n’ Ballads
Duration: 01:08:44.291
URL     : https://musicbrainz.org/release/b0008a33-6a71-4a31-80f9-ceaa4afd1366
Release : b0008a33-6a71-4a31-80f9-ceaa4afd1366
Type    : Compilation
Barcode : 077779343928
Cat no  : CDP 566Y 793439 2

Traceback (most recent call last):
  File "/usr/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.7.3', 'console_scripts', 'whipper')()
  File "/usr/lib/python2.7/dist-packages/whipper/command/main.py", line 43, in main
    ret = cmd.do()
  File "/usr/lib/python2.7/dist-packages/whipper/command/basecommand.py", line 139, in do
    return self.cmd.do()
  File "/usr/lib/python2.7/dist-packages/whipper/command/basecommand.py", line 139, in do
    return self.cmd.do()
  File "/usr/lib/python2.7/dist-packages/whipper/command/cd.py", line 150, in do
    out_fpath)
  File "/usr/lib/python2.7/dist-packages/whipper/common/program.py", line 125, in getTable
    t = cdrdao.ReadTableTask(device, out_path)
  File "/usr/lib/python2.7/dist-packages/whipper/program/cdrdao.py", line 102, in ReadTableTask
    return read_toc(device, toc_path=toc_path)
  File "/usr/lib/python2.7/dist-packages/whipper/program/cdrdao.py", line 46, in read_toc
    toc.parse()
  File "/usr/lib/python2.7/dist-packages/whipper/image/toc.py", line 233, in parse
    self._index(currentTrack, 1, absoluteOffset, pregapLength)
  File "/usr/lib/python2.7/dist-packages/whipper/image/toc.py", line 160, in _index
    currentTrack.index(i, path=s.path,
AttributeError: 'NoneType' object has no attribute 'path'

Whipper.conf:
[main]
path_filter_fat = True          ; replace FAT file system unsafe characters in filenames with _
path_filter_special = False     ; replace special characters in filenames with _

[drive:PLDS%20%20%20%20%3ADVD-RW%20DH16ABSH%20%3AYL32]
vendor = PLDS
model = DVD-RW DH16ABSH
release = YL32
defeats_cache = True
read_offset = 6

[whipper.cd.rip]
output_directory = ~/
working_directory = ~/
track_template = %%A/%%d/%%t - %%a - %%n
disc_template = %%A/%%d/%%A - %%d

What might be wrong?

**Comment by jtl999** [comment] 2018-12-31 18:33
I could be wrong, but it could be that Whipper doesn't properly expand the `~` pseudo path.

My personal recommendation is setting `working_directory` to `/path/` where `/path/` is the path you want the album to be ripped and leaving `output_directory` unset. This means there's no privacy concerns of file paths containing your name, etc are in the logfile output.

**Comment by janifr** [comment] 2019-01-01 16:03
Thank you, that did the trick.

**Comment by JoeLametta** [comment] 2019-01-17 22:35
Hi, thanks for the bug report! Unfortunately I'm quite busy at the moment.
Just noticed this looks like the same traceback as in #145...

**Comment by Freso** [comment] 2019-05-01 17:52
Duplicate of https://github.com/whipper-team/whipper/issues/145 – please continue debugging and discussion there.

**Closed by Freso** 2019-05-01 17:52 UTC
Labels: Duplicate
