### ISSUE TITLE
CRITICAL:whipper.command.main:exception TypeError

### ISSUE THREAD

**Issue by pimmel12** [whipper-team/whipper#496] opened 2020-07-08 17:23 UTC
Fedora 32 -  "whipper drive analyze" ends as:

CRITICAL:whipper.command.main:exception TypeError at /usr/lib64/python3.8/site-packages/whipper/program/cdparanoia.py:606: failed(): sequence item 0: expected str instance, bytes found
Traceback (most recent call last):
  File "/usr/lib64/python3.8/site-packages/whipper/common/task.py", line 89, in _read
    self._done()
  File "/usr/lib64/python3.8/site-packages/whipper/common/task.py", line 107, in _done
    self.failed()
  File "/usr/lib64/python3.8/site-packages/whipper/program/cdparanoia.py", line 606, in failed
    output = "".join(self._output)
TypeError: sequence item 0: expected str instance, bytes found

**Comment by JoeLametta** [comment] 2020-07-09 14:50
Hi, this appears to be a duplicate of issue #431 which was fixed in pull request #434 (commit [29ee670](https://github.com/whipper-team/whipper/commit/29ee670b7fa6ec7402c774091b893d5414e59bc0)). We still need to tag an updated version of whipper...

**Comment by BachoSeven** [comment] 2020-07-19 14:32
@JoeLametta Thanks, upstream fixed this!

**Closed** 2020-08-10 14:51 UTC
Labels: Duplicate
