### ISSUE TITLE
cdparanoia couldn't read any frames for the current track

### ISSUE THREAD

**Issue by tlc** [whipper-team/whipper#356] opened 2019-01-17 18:41 UTC
My old hand install of 0.5.1 rips this CD, but when I try to use a recent docker pull (0.7.3), I get the following.

```

$ whipper cd rip
INFO:whipper.command.cd:using configured read offset 667
INFO:whipper.command.cd:checking device /dev/sr0
INFO:whipper.command.cd:reading TOC...
CDDB disc id: b00d110f
MusicBrainz disc id ucwSu9i1CuqKVP6_DtpiYBL8tbg-
MusicBrainz lookup URL https://musicbrainz.org/cdtoc/attach?toc=1+15+251048+150+15764+34126+51995+69726+87145+103034+120127+135853+153375+169449+185312+202590+218125+233388&tracks=15&id=ucwSu9i1CuqKVP6_DtpiYBL8tbg-
Disc duration: 00:55:45.306, 15 audio tracks
INFO:musicbrainzngs:in <ws2:release-group>, uncaught attribute type-id

Matching releases:

Artist  : Taylor Swift
Title   : reputation
Duration: 00:55:38.000
URL     : https://musicbrainz.org/release/fe55bc3b-6d42-4fa1-9366-a57c18a806d4
Release : fe55bc3b-6d42-4fa1-9366-a57c18a806d4
Type    : Album
Barcode : 843930033102
Cat no  : BMRCO0600A

INFO:whipper.command.cd:ripping track 1 of 15: 01. Taylor Swift - …Ready for It_.flac
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 36724172
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
Traceback (most recent call last):      
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.3-py2.7.egg/whipper/extern/task/task.py", line 518, in c
    callable(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.3-py2.7.egg/whipper/program/cdparanoia.py", line 316, in _read
    self._done()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.3-py2.7.egg/whipper/program/cdparanoia.py", line 392, in _done
    self.quality = self._parser.getTrackQuality()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.3-py2.7.egg/whipper/program/cdparanoia.py", line 200, in getTrackQuality
    raise RuntimeError("cdparanoia couldn't read any frames "
RuntimeError: cdparanoia couldn't read any frames for the current track
INFO:whipper.command.cd:ripping track 1 of 15 (try 2): 01. Taylor Swift - …Ready for It_.flac
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 36724172
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
Traceback (most recent call last):              
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.3-py2.7.egg/whipper/extern/task/task.py", line 518, in c
    callable(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.3-py2.7.egg/whipper/program/cdparanoia.py", line 316, in _read
    self._done()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.3-py2.7.egg/whipper/program/cdparanoia.py", line 392, in _done
    self.quality = self._parser.getTrackQuality()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.3-py2.7.egg/whipper/program/cdparanoia.py", line 200, in getTrackQuality
    raise RuntimeError("cdparanoia couldn't read any frames "
RuntimeError: cdparanoia couldn't read any frames for the current track
INFO:whipper.command.cd:ripping track 1 of 15 (try 3): 01. Taylor Swift - …Ready for It_.flac
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 36724172
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
Traceback (most recent call last):              
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.3-py2.7.egg/whipper/extern/task/task.py", line 518, in c
    callable(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.3-py2.7.egg/whipper/program/cdparanoia.py", line 316, in _read
    self._done()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.3-py2.7.egg/whipper/program/cdparanoia.py", line 392, in _done
    self.quality = self._parser.getTrackQuality()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.3-py2.7.egg/whipper/program/cdparanoia.py", line 200, in getTrackQuality
    raise RuntimeError("cdparanoia couldn't read any frames "
RuntimeError: cdparanoia couldn't read any frames for the current track
INFO:whipper.command.cd:ripping track 1 of 15 (try 4): 01. Taylor Swift - …Ready for It_.flac
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 36724172
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
Traceback (most recent call last):              
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.3-py2.7.egg/whipper/extern/task/task.py", line 518, in c
    callable(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.3-py2.7.egg/whipper/program/cdparanoia.py", line 316, in _read
    self._done()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.3-py2.7.egg/whipper/program/cdparanoia.py", line 392, in _done
    self.quality = self._parser.getTrackQuality()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.3-py2.7.egg/whipper/program/cdparanoia.py", line 200, in getTrackQuality
    raise RuntimeError("cdparanoia couldn't read any frames "
RuntimeError: cdparanoia couldn't read any frames for the current track
INFO:whipper.command.cd:ripping track 1 of 15 (try 5): 01. Taylor Swift - …Ready for It_.flac
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 36724172
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
Traceback (most recent call last):              
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.3-py2.7.egg/whipper/extern/task/task.py", line 518, in c
    callable(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.3-py2.7.egg/whipper/program/cdparanoia.py", line 316, in _read
    self._done()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.3-py2.7.egg/whipper/program/cdparanoia.py", line 392, in _done
    self.quality = self._parser.getTrackQuality()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.3-py2.7.egg/whipper/program/cdparanoia.py", line 200, in getTrackQuality
    raise RuntimeError("cdparanoia couldn't read any frames "
RuntimeError: cdparanoia couldn't read any frames for the current track
CRITICAL:whipper.command.cd:giving up on track 1 after 5 times
track can't be ripped. Rip attempts number is equal to 'MAX_TRIES'

```

**Comment by JoeLametta** [comment] 2019-01-17 22:04
Thanks for the bug report.
This issue is a duplicate of #234 (a know [upstream bug](https://github.com/rocky/libcdio-paranoia/issues/14)): let's keep discussing it in [that ticket](https://github.com/whipper-team/whipper/issues/234).

Cheers,
JoeLametta

**Closed by JoeLametta** 2019-01-17 22:04 UTC
Labels: Duplicate
