### ISSUE TITLE
whipper drive analyze is stuck at "Analyzing drive caching behaviour 0 %"

### ISSUE THREAD

**Issue by Markus-N** [whipper-team/whipper#502] opened 2020-08-01 13:01 UTC
I've let it run for 16 hours now, the drive's LED is blinking, but no progress. I'm willing to help debugging this issue. Just need some advice (I'm a developer, but I have nearly no Python experience).

**System and version info:**
* whipper whipper 0.9.0-1 installed from the official package on Arch Linux.
* Python is version 3.8.5
* cdparanoia is version 10.2-8

    whipper drive list
    drive: /dev/cdrom, vendor: HL-DT-ST, model: BDDVDRW CH12NS40, release: 1.01

**Comment by Markus-N** [comment] 2020-08-01 14:05
**Steps to reproduce:**
* Put a CD into the drive
* run `WHIPPER_DEBUG=DEBUG WHIPPER_LOGFILE=whipper.log whipper drive analyze -d /dev/cdrom`
* Cancel after a while using `Ctrl-C`

**Result:**
See log attached log.

[whipper.log.gz](https://github.com/whipper-team/whipper/files/5010591/whipper.log.gz)

**Comment by Markus-N** [comment] 2020-08-03 07:53
I just did a cross-check by using `cdparanoia --analyze-drive` directly. It took very long (47m55,312s) for the same CD, but at least didn't get stuck.

**Comment by JoeLametta** [comment] 2020-08-10 12:13
Hi, this appears to be a duplicate of [issue #469](https://github.com/whipper-team/whipper/issues/469).

**Closed** 2020-09-10 08:25 UTC
Labels: Duplicate
