### ISSUE TITLE
.cue file gaps are non-compliant

### ISSUE THREAD

**Issue by kroeckx** [whipper-team/whipper#442] opened 2020-01-01 19:22 UTC
I ripped a CD, and the .cue file contains:
```
REM DISCID A70F8F0C
REM COMMENT "whipper 0.9.1.dev16+gd665fe4"
FILE "./01. Dire Straits - Sultans of Swing.flac" WAVE
  TRACK 01 AUDIO
    PREGAP 00:00:33
    INDEX 01 00:00:00
FILE "./02. Dire Straits - Down to the Waterline.flac" WAVE
  TRACK 02 AUDIO
    INDEX 01 00:00:00
  TRACK 03 AUDIO
    INDEX 00 04:00:18
FILE "./03. Dire Straits - Portobello Belle (live).flac" WAVE
    INDEX 01 00:00:00
  TRACK 04 AUDIO
    INDEX 00 04:32:52
FILE "./04. Dire Straits - Twisting by the Pool (remix).flac" WAVE
    INDEX 01 00:00:00
  TRACK 05 AUDIO
    INDEX 00 03:30:02
FILE "./05. Dire Straits - Tunnel of Love.flac" WAVE
    INDEX 01 00:00:00
  TRACK 06 AUDIO
    INDEX 00 08:09:03
FILE "./06. Dire Straits - Romeo and Juliet.flac" WAVE
    INDEX 01 00:00:00
FILE "./07. Dire Straits - Where Do You Think You're Going.flac" WAVE
  TRACK 07 AUDIO
    INDEX 01 00:00:00
FILE "./08. Dire Straits - Walk of Life.flac" WAVE
  TRACK 08 AUDIO
    INDEX 01 00:00:00
  TRACK 09 AUDIO
    INDEX 00 04:07:32
FILE "./09. Dire Straits - Private Investigations.flac" WAVE
    INDEX 01 00:00:00
FILE "./10. Dire Straits - Telegraph Road (live) (remix).flac" WAVE
  TRACK 10 AUDIO
    INDEX 01 00:00:00
FILE "./11. Dire Straits - Money for Nothing.flac" WAVE
  TRACK 11 AUDIO
    INDEX 01 00:00:00
  TRACK 12 AUDIO
    INDEX 00 04:05:10
FILE "./12. Dire Straits - Brothers in Arms.flac" WAVE
    INDEX 01 00:00:00
```

**Comment by JoeLametta** [comment] 2020-01-03 11:09
Hi, isn't this a duplicate of #265 (which is not a bug)?

**Comment by kroeckx** [comment] 2020-01-03 18:02
The hydrogenaudio wiki it points to says "Unfortunately, this format is non-compliant". Wikipedia calls it non-standard and non-conforming.

https://github.com/libyal/libodraw/blob/master/documentation/CUE%20sheet%20format.asciidoc seems to be an attempt to standardize the cue format, but it doesn't try to fix that.

The software I tried to parse the file with didn't support it. Other software clearly would benefit from having a standard document that at least explains this extension.

**Comment by JoeLametta** [comment] 2020-01-04 13:23
This is the format preferred/used/expected by most of the audio CD ripping software: [EAC](http://www.exactaudiocopy.de/), [XLD](https://tmkk.undo.jp/xld/index_e.html), [CUERipper](http://cue.tools/wiki/CUERipper). For each rip whipper writes a [cdrdao](http://cdrdao.sourceforge.net/)'s tocfile too which allows burning the rip to a CD.
There's also a FOSS software which is able to convert cue sheets (and the associated files) to various formats: [CUETools](http://cue.tools/wiki/CUETools).

This issue may be also related to #115.

**Comment by kroeckx** [comment] 2020-01-04 15:33
There is also https://github.com/svend/cuetools that gives errors on both the .cue and .toc file.

**Comment by JoeLametta** [comment] 2020-01-04 15:44
You can generate toc files from non-compliant cue sheets using [mktoc](https://github.com/whipper-team/mktoc) (FOSS software).

**Closed** 2020-01-29 12:50 UTC
Labels: Expected Behaviour
