### ISSUE TITLE
TypeError cdparanoia.py:606

### ISSUE THREAD

**Issue by volker-raschek** [whipper-team/whipper#526] opened 2021-02-24 17:47 UTC
Hello, 
I would like to analyze my drive but I receive the following error:

```bash
$ whipper drive analyze
CRITICAL:whipper.command.main:exception TypeError at /usr/lib/python3.9/site-packages/whipper/program/cdparanoia.py:606: failed(): sequence item 0: expected str instance, bytes found
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/whipper/common/task.py", line 89, in _read
    self._done()
  File "/usr/lib/python3.9/site-packages/whipper/common/task.py", line 107, in _done
    self.failed()
  File "/usr/lib/python3.9/site-packages/whipper/program/cdparanoia.py", line 606, in failed
    output = "".join(self._output)
TypeError: sequence item 0: expected str instance, bytes found
``` 

It there a workaround or must I wait until this bug has been fixed?

Whipper: 0.9.0-2
OS: Arch Linux 
Python: 3.9
Kernel: 5.10.16

Volker

**Comment by JoeLametta** [comment] 2021-03-11 09:18
Hi, this is a duplicate of a known bug (#431) already fixed in whipper develop (#434) but not yet in a tagged whipper version.

**Closed** 2021-05-14 07:51 UTC
Labels: Bug, Duplicate
